name: Publish Application on GitHub Pages to ScheduleAAG.github.io
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy Kotlin/Wasm
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Check out code
        uses: actions/checkout@v4

      - name: Generate AppConfig
        run: ./gradlew :composeApp:generateAppConfig

      - name: UpgradeYarnLockFile
        run: ./gradlew :composeApp:kotlinWasmUpgradeYarnLock

      - name: Build WebApp
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Deploy to ScheduleAAG.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_SSH_KEY }}
          external_repository: ScheduleAAG/ScheduleAAG.github.io
          publish_branch: gh-pages
          publish_dir: ./composeApp/build/dist/wasmJs/productionExecutable/